name: Build Custom Kernel 1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup build environment
        run: |
          sudo apt update
          sudo apt install -y build-essential bc bison flex libssl-dev ccache \
            gcc-aarch64-linux-gnu git wget curl unzip python3 zip

      - name: Download clang toolchain (Google AOSP)
        run: |
          mkdir -p toolchains
          cd toolchains
          wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/master/clang-r498229.tar.gz -O clang.tar.gz
          mkdir clang
          tar -xf clang.tar.gz -C clang
          echo "TOOLCHAIN=$PWD/clang" >> $GITHUB_ENV

      - name: Add Jonjeexe and tweaks to config
        run: |
          echo "CONFIG_ZRAM=y" >> arch/arm64/configs/defconfig
          echo "CONFIG_ZSWAP=y" >> arch/arm64/configs/defconfig
          echo "CONFIG_ZSMALLOC=y" >> arch/arm64/configs/defconfig
          # Append local version
          sed -i '/EXTRAVERSION/c\EXTRAVERSION = -Jonjeexe' Makefile

      - name: Build Kernel
        run: |
          set -e
          exec > >(tee build.log) 2>&1
          export PATH=$TOOLCHAIN/bin:$PATH
          export ARCH=arm64
          export SUBARCH=arm64
          DEFCONFIG="defconfig"
          echo "Using defconfig: $DEFCONFIG"
          make O=out $DEFCONFIG CC=clang CROSS_COMPILE=aarch64-linux-gnu-
          make -j$(nproc) O=out CC=clang CROSS_COMPILE=aarch64-linux-gnu-
          echo "Build completed"

      - name: Prepare artifacts directory
        if: always()
        run: |
          mkdir -p output
          cp out/arch/arm64/boot/Image* output/ || true
          cp -r out/arch/arm64/boot/dts output/ || true
          cp build.log output/ || true

      - name: Upload to Telegram
        if: always()
        env:
          TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -s -F document=@output/build.log "https://api.telegram.org/bot$TOKEN/sendDocument" -F chat_id=$CHAT_ID -F caption="Kernel Build Log"
          if ls output/Image* 1> /dev/null 2>&1; then
            cd output
            zip -r kernel_output.zip Image* dts || true
            curl -s -F document=@kernel_output.zip "https://api.telegram.org/bot$TOKEN/sendDocument" -F chat_id=$CHAT_ID -F caption="Kernel Build Output"
          else
            echo "No kernel image built; only log sent."
          fi

      - name: Upload artifact to GitHub
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: kernel-build
          path: output
          
